/*
 *
 * LiveShare constants
 *
 */

export const HUB_CONNECTION_REQUEST = 'app/LiveShare/HUB_CONNECTION_REQUEST'
export const HUB_CONNECTION_SUCCESS = 'app/LiveShare/HUB_CONNECTION_SUCCESS'
export const HUB_CONNECTION_FAILURE = 'app/LiveShare/HUB_CONNECTION_FAILURE'

export const SEND_MESSAGE_REQUEST = 'app/LiveShare/SEND_MESSAGE_REQUEST'
export const SEND_MESSAGE_SUCCESS = 'app/LiveShare/SEND_MESSAGE_SUCCESS'
export const SEND_MESSAGE_FAILURE = 'app/LiveShare/SEND_MESSAGE_FAILURE'

export const LOAD_SKILL_INSTANCE_REQUEST =
  'app/LiveShare/LOAD_SKILL_INSTANCE_REQUEST'
export const LOAD_SKILL_INSTANCE_SUCCESS =
  'app/LiveShare/LOAD_SKILL_INSTANCE_SUCCESS'
export const LOAD_SKILL_INSTANCE_FAILURE =
  'app/LiveShare/LOAD_SKILL_INSTANCE_FAILURE'

export const UNLOAD_SKILL_INSTANCE_REQUEST =
  'app/LiveShare/UNLOAD_SKILL_INSTANCE_REQUEST'
export const UNLOAD_SKILL_INSTANCE_SUCCESS =
  'app/LiveShare/UNLOAD_SKILL_INSTANCE_SUCCESS'
export const UNLOAD_SKILL_INSTANCE_FAILURE =
  'app/LiveShare/UNLOAD_SKILL_INSTANCE_FAILURE'

export const COLLABORATOR_JOINED_EVENT_REQUEST =
  'app/LiveShare/COLLABORATOR_JOINED_EVENT_REQUEST'
export const COLLABORATOR_LEFT_EVENT_REQUEST =
  'app/LiveShare/COLLABORATOR_LEFT_EVENT_REQUEST'
export const PATCH_RECEIVED_EVENT_REQUEST =
  'app/LiveShare/PATCH_RECEIVED_EVENT_REQUEST'
export const SET_CHANGE_TRACKING_REQUEST =
  'app/LiveShare/SET_CHANGE_TRACKING_REQUEST'
export const SET_SKILL_DATA_REQUEST = 'app/LiveShare/SET_SKILL_DATA_REQUEST'
export const CHAT_MESSAGE_RECEIVED_REQUEST =
  'app/LiveShare/CHAT_MESSAGE_RECEIVED_REQUEST'
export const ADD_CONTENT_OPERATIONS_REQUEST =
  'app/LiveShare/ADD_CONTENT_OPERATIONS_REQUEST'
export const SET_PAGE_CONTENT_REQUEST = 'app/LiveShare/SET_PAGE_CONTENT_REQUEST'
export const LIVESHARE_NODE_OPERATION_RECEIVED_REQUEST =
  'app/LiveShare/LIVESHARE_NODE_OPERATION_RECEIVED_REQUEST'
export const LIVESHARE_LINK_OPERATION_RECEIVED_REQUEST =
  'app/LiveShare/LIVESHARE_LINK_OPERATION_RECEIVED_REQUEST'

export const COLLABORATOR_JOINED_EVENT_FAILURE =
  'app/LiveShare/COLLABORATOR_JOINED_EVENT_FAILURE'
export const COLLABORATOR_LEFT_EVENT_FAILURE =
  'app/LiveShare/COLLABORATOR_LEFT_EVENT_FAILURE'
export const PATCH_RECEIVED_EVENT_FAILURE =
  'app/LiveShare/PATCH_RECEIVED_EVENT_FAILURE'
export const SET_CHANGE_TRACKING_FAILURE =
  'app/LiveShare/SET_CHANGE_TRACKING_FAILURE'
export const SET_SKILL_DATA_FAILURE = 'app/LiveShare/SET_SKILL_DATA_FAILURE'
export const CHAT_MESSAGE_RECEIVED_FAILURE =
  'app/LiveShare/CHAT_MESSAGE_RECEIVED_FAILURE'
export const ADD_CONTENT_OPERATIONS_FAILURE =
  'app/LiveShare/ADD_CONTENT_OPERATIONS_FAILURE'
export const SET_PAGE_CONTENT_FAILURE = 'app/LiveShare/SET_PAGE_CONTENT_FAILURE'
export const LIVESHARE_NODE_OPERATION_RECEIVED_FAILURE =
  'app/LiveShare/LIVESHARE_NODE_OPERATION_RECEIVED_FAILURE'
export const LIVESHARE_LINK_OPERATION_RECEIVED_FAILURE =
  'app/LiveShare/LIVESHARE_LINK_OPERATION_RECEIVED_FAILURE'

export const COLLABORATOR_JOINED_EVENT_SUCCESS =
  'app/LiveShare/COLLABORATOR_JOINED_EVENT_SUCCESS'
export const COLLABORATOR_LEFT_EVENT_SUCCESS =
  'app/LiveShare/COLLABORATOR_LEFT_EVENT_SUCCESS'
export const PATCH_RECEIVED_EVENT_SUCCESS =
  'app/LiveShare/PATCH_RECEIVED_EVENT_SUCCESS'
export const SET_CHANGE_TRACKING_SUCCESS =
  'app/LiveShare/SET_CHANGE_TRACKING_SUCCESS'
export const SET_SKILL_DATA_SUCCESS = 'app/LiveShare/SET_SKILL_DATA_SUCCESS'
export const CHAT_MESSAGE_RECEIVED_SUCCESS =
  'app/LiveShare/CHAT_MESSAGE_RECEIVED_SUCCESS'
export const ADD_CONTENT_OPERATIONS_SUCCESS =
  'app/LiveShare/ADD_CONTENT_OPERATIONS_SUCCESS'
export const SET_PAGE_CONTENT_SUCCESS = 'app/LiveShare/SET_PAGE_CONTENT_SUCCESS'
export const LIVESHARE_NODE_OPERATION_RECEIVED_SUCCESS =
  'app/LiveShare/LIVESHARE_NODE_OPERATION_RECEIVED_SUCCESS'
export const LIVESHARE_LINK_OPERATION_RECEIVED_SUCCESS =
  'app/LiveShare/LIVESHARE_LINK_OPERATION_RECEIVED_SUCCESS'

export const SEND_PATCH_REQUEST = 'app/LiveShare/SEND_PATCH_REQUEST'
export const SEND_PATCH_SUCCESS = 'app/LiveShare/SEND_PATCH_SUCCESS'
export const SEND_PATCH_FAILURE = 'app/LiveShare/SEND_PATCH_FAILURE'

export const SEND_CHAT_MESSAGE_REQUEST =
  'app/LiveShare/SEND_CHAT_MESSAGE_REQUEST'
export const SEND_CHAT_MESSAGE_SUCCESS =
  'app/LiveShare/SEND_CHAT_MESSAGE_SUCCESS'
export const SEND_CHAT_MESSAGE_FAILURE =
  'app/LiveShare/SEND_CHAT_MESSAGE_FAILURE'

export const SEND_CONTENT_OPERATION_REQUEST =
  'app/LiveShare/SEND_CONTENT_OPERATION_REQUEST'
export const SEND_CONTENT_OPERATION_SUCCESS =
  'app/LiveShare/SEND_CONTENT_OPERATION_SUCCESS'
export const SEND_CONTENT_OPERATION_FAILURE =
  'app/LiveShare/SEND_CONTENT_OPERATION_FAILURE'

export const HEARTBEAT_REQUEST = 'app/LiveShare/HEARTBEAT_REQUEST'
export const HEARTBEAT_SUCCESS = 'app/LiveShare/HEARTBEAT_SUCCESS'
export const HEARTBEAT_FAILURE = 'app/LiveShare/HEARTBEAT_FAILURE'

export const ADD_USER_SELECTION_REQUEST =
  'app/LiveShare/ADD_USER_SELECTION_REQUEST'
export const ADD_USER_SELECTION_SUCCESS =
  'app/LiveShare/ADD_USER_SELECTION_SUCCESS'
export const ADD_USER_SELECTION_FAILURE =
  'app/LiveShare/ADD_USER_SELECTION_FAILURE'
