/*
 *
 * Graphnos constants
 *
 */

export const FETCH_GRAPH_REQUEST = 'app/Graphnos/FETCH_GRAPH_REQUEST'
export const FETCH_GRAPH_SUCCESS = 'app/Graphnos/FETCH_GRAPH_SUCCESS'
export const FETCH_GRAPH_FAILURE = 'app/Graphnos/FETCH_GRAPH_FAILURE'

export const CREATE_NODE_REQUEST = 'app/Graphnos/CREATE_NODE_REQUEST'
export const CREATE_NODE_SUCCESS = 'app/Graphnos/CREATE_NODE_SUCCESS'
export const CREATE_NODE_FAILURE = 'app/Graphnos/CREATE_NODE_FAILURE'

export const UPDATE_NODE_REQUEST = 'app/Graphnos/UPDATE_NODE_REQUEST'
export const UPDATE_NODE_SUCCESS = 'app/Graphnos/UPDATE_NODE_SUCCESS'
export const UPDATE_NODE_FAILURE = 'app/Graphnos/UPDATE_NODE_FAILURE'

export const DELETE_NODE_REQUEST = 'app/Graphnos/DELETE_NODE_REQUEST'
export const DELETE_NODE_SUCCESS = 'app/Graphnos/DELETE_NODE_SUCCESS'
export const DELETE_NODE_FAILURE = 'app/Graphnos/DELETE_NODE_FAILURE'

export const CREATE_DEPENDENCY_REQUEST =
  'app/Graphnos/CREATE_DEPENDENCY_REQUEST'
export const CREATE_DEPENDENCY_SUCCESS =
  'app/Graphnos/CREATE_DEPENDENCY_SUCCESS'
export const CREATE_DEPENDENCY_FAILURE =
  'app/Graphnos/CREATE_DEPENDENCY_FAILURE'

export const UPDATE_DEPENDENCY_REQUEST =
  'app/Graphnos/UPDATE_DEPENDENCY_REQUEST'
export const UPDATE_DEPENDENCY_SUCCESS =
  'app/Graphnos/UPDATE_DEPENDENCY_SUCCESS'
export const UPDATE_DEPENDENCY_FAILURE =
  'app/Graphnos/UPDATE_DEPENDENCY_FAILURE'

export const DELETE_DEPENDENCY_REQUEST =
  'app/Graphnos/DELETE_DEPENDENCY_REQUEST'
export const DELETE_DEPENDENCY_SUCCESS =
  'app/Graphnos/DELETE_DEPENDENCY_SUCCESS'
export const DELETE_DEPENDENCY_FAILURE =
  'app/Graphnos/DELETE_DEPENDENCY_FAILURE'

export const LOAD_SIMULATED_GRAPH = 'app/Graphnos/LOAD_SIMULATED_GRAPH'
export const UPDATE_SIMULATION_NODE = 'app/Graphnos/UPDATE_SIMULATION_NODE'

export const DUPLICATE_SKILL_REQUEST = 'app/Graphnos/DUPLICATE_SKILL_REQUEST'
export const DUPLICATE_SKILL_FAILURE = 'app/Graphnos/DUPLICATE_SKILL_FAILURE'
export const RESET_SIMULATION = 'app/Graphnos/RESET_SIMULATION'
export const FINISH_SIMULATION = 'app/Graphnos/FINISH_SIMULATION'

export const APPLY_PBRO_REQUEST = 'app/Graphnos/APPLY_PBRO_REQUEST'
export const APPLY_PBRO_SUCCESS = 'app/Graphnos/APPLY_PBRO_SUCCESS'
export const APPLY_PBRO_FAILURE = 'app/Graphnos/APPLY_PBRO_FAILURE'

export const APPLY_REVERSE_PBRO_REQUEST =
  'app/Graphnos/APPLY_REVERSE_PBRO_REQUEST'
export const APPLY_REVERSE_PBRO_SUCCESS =
  'app/Graphnos/APPLY_REVERSE_PBRO_SUCCESS'
export const APPLY_REVERSE_PBRO_FAILURE =
  'app/Graphnos/APPLY_REVERSE_PBRO_FAILURE'

export const MAGNIFY_REQUEST = 'app/Graphnos/MAGNIFY_REQUEST'
export const MAGNIFY_SUCCESS = 'app/Graphnos/MAGNIFY_SUCCESS'
export const MAGNIFY_FAILURE = 'app/Graphnos/MAGNIFY_FAILURE'

export const REDIRECT_TO_EDITOR = 'app/Graphnos/REDIRECT_TO_EDITOR'

export const UPDATE_TRACK_FILTER_REQUEST =
  'app/Graphnos/UPDATE_TRACK_FILTER_REQUEST'
export const UPDATE_TRACK_FILTER_SUCCESS =
  'app/Graphnos/UPDATE_TRACK_FILTER_SUCCESS'
export const UPDATE_TRACK_FILTER_FAILURE =
  'app/Graphnos/UPDATE_TRACK_FILTER_FAILURE'

export const UPDATE_NODE_FILTER_REQUEST =
  'app/Graphnos/UPDATE_NODE_FILTER_REQUEST'
export const UPDATE_NODE_FILTER_SUCCESS =
  'app/Graphnos/UPDATE_NODE_FILTER_SUCCESS'
export const UPDATE_NODE_FILTER_FAILURE =
  'app/Graphnos/UPDATE_NODE_FILTER_FAILURE'

export const SELECT_NODE_REQUEST = 'app/Graphnos/SELECT_NODE_REQUEST'
export const SELECT_NODE_SUCCESS = 'app/Graphnos/SELECT_NODE_SUCCESS'
export const SELECT_NODE_FAILURE = 'app/Graphnos/SELECT_NODE_FAILURE'

export const SET_PREVIOUS_NODE_REQUEST =
  'app/Graphnos/SET_PREVIOUS_NODE_REQUEST'
export const SET_PREVIOUS_NODE_SUCCESS =
  'app/Graphnos/SET_PREVIOUS_NODE_SUCCESS'
export const SET_PREVIOUS_NODE_FAILURE =
  'app/Graphnos/SET_PREVIOUS_NODE_FAILURE'

export const SET_LINK_REQUEST = 'app/Graphnos/SET_LINK_REQUEST'
export const SET_LINK_SUCCESS = 'app/Graphnos/SET_LINK_SUCCESS'
export const SET_LINK_FAILURE = 'app/Graphnos/SET_LINK_FAILURE'

export const UPDATE_WEIGHT_REQUEST = 'app/Graphnos/UPDATE_WEIGHT_REQUEST'
export const UPDATE_WEIGHT_SUCCESS = 'app/Graphnos/UPDATE_WEIGHT_SUCCESS'
export const UPDATE_WEIGHT_FAILURE = 'app/Graphnos/UPDATE_WEIGHT_FAILURE'

export const SET_SHOW_MODAL_REQUEST = 'app/Graphnos/SET_SHOW_MODAL_REQUEST'
export const SET_SHOW_MODAL_SUCCESS = 'app/Graphnos/SET_SHOW_MODAL_SUCCESS'
export const SET_SHOW_MODAL_FAILURE = 'app/Graphnos/SET_SHOW_MODAL_FAILURE'

export const CLEAR_REDUCER_REQUEST = 'app/Graphnos/CLEAR_REDUCER_REQUEST'
export const CLEAR_REDUCER_SUCCESS = 'app/Graphnos/CLEAR_REDUCER_SUCCESS'
export const CLEAR_REDUCER_FAILURE = 'app/Graphnos/CLEAR_REDUCER_FAILURE'
