/*
 *
 * Issues constants
 *
 */

export const FETCH_ISSUES_REQUEST = 'app/Issues/FETCH_ISSUES_REQUEST'
export const FETCH_ISSUES_SUCCESS = 'app/Issues/FETCH_ISSUES_SUCCESS'
export const FETCH_ISSUES_FAILURE = 'app/Issues/FETCH_ISSUES_FAILURE'

export const UPDATE_STATUS_REQUEST = 'app/Issues/UPDATE_STATUS_REQUEST'
export const UPDATE_STATUS_SUCCESS = 'app/Issues/UPDATE_STATUS_SUCCESS'
export const UPDATE_STATUS_FAILURE = 'app/Issues/UPDATE_STATUS_FAILURE'

export const SET_IS_MARK_AS_MODAL_VISIBLE_REQUEST =
  'app/Issues/SET_IS_MARK_AS_MODAL_VISIBLE_REQUEST'
export const SET_IS_MARK_AS_MODAL_VISIBLE_SUCCESS =
  'app/Issues/SET_IS_MARK_AS_MODAL_VISIBLE_SUCCESS'
export const SET_IS_MARK_AS_MODAL_VISIBLE_FAILURE =
  'app/Issues/SET_IS_MARK_AS_MODAL_VISIBLE_FAILURE'

export const SET_IS_ASSIGN_TO_PROJECT_MODAL_VISIBLE_REQUEST =
  'app/Issues/SET_IS_ASSIGN_TO_PROJECT_MODAL_VISIBLE_REQUEST'
export const SET_IS_ASSIGN_TO_PROJECT_MODAL_VISIBLE_SUCCESS =
  'app/Issues/SET_IS_ASSIGN_TO_PROJECT_MODAL_VISIBLE_SUCCESS'
export const SET_IS_ASSIGN_TO_PROJECT_MODAL_VISIBLE_FAILURE =
  'app/Issues/SET_IS_ASSIGN_TO_PROJECT_MODAL_VISIBLE_FAILURE'
