/*
 *
 * Sprints constants
 *
 */

export const FETCH_SPRINTS_FIRST_TIME_REQUEST =
  'app/Sprints/FETCH_SPRINTS_FIRST_TIME_REQUEST'
export const FETCH_SPRINTS_FIRST_TIME_SUCCESS =
  'app/Sprints/FETCH_SPRINTS_FIRST_TIME_SUCCESS'
export const FETCH_SPRINTS_FIRST_TIME_FAILURE =
  'app/Sprints/FETCH_SPRINTS_FAILURE'

export const ADD_SPRINT_FIRST_TIME_REQUEST =
  'app/Sprints/ADD_SPRINT_FIRST_TIME_REQUEST'
export const ADD_SPRINT_FIRST_TIME_SUCCESS =
  'app/Sprints/ADD_SPRINT_FIRST_TIME_SUCCESS'
export const ADD_SPRINT_FIRST_TIME_FAILURE = 'app/Sprints/ADD_SPRINT_FAILURE'

export const FETCH_SPRINTS_REQUEST = 'app/Sprints/FETCH_SPRINTS_REQUES3T'
export const FETCH_SPRINTS_SUCCESS = 'app/Sprints/FETCH_SPRINTS_SUCCESS'
export const FETCH_SPRINTS_FAILURE = 'app/Sprints/FETCH_SPRINTS_FAILURE'

export const FETCH_WORK_ITEMS_REQUEST = 'app/Sprints/FETCH_WORK_ITEMS_REQUEST'
export const FETCH_WORK_ITEMS_SUCCESS = 'app/Sprints/FETCH_WORK_ITEMS_SUCCESS'
export const FETCH_WORK_ITEMS_FAILURE = 'app/Sprints/FETCH_WORK_ITEMS_FAILURE'

export const ADD_SPRINT_REQUEST = 'app/Sprints/ADD_SPRINT_REQUEST'
export const ADD_SPRINT_SUCCESS = 'app/Sprints/ADD_SPRINT_SUCCESS'
export const ADD_SPRINT_FAILURE = 'app/Sprints/ADD_SPRINT_FAILURE'

export const ADD_WORK_ITEM_REQUEST = 'app/Sprints/ADD_WORK_ITEM_REQUEST'
export const ADD_WORK_ITEM_SUCCESS = 'app/Sprints/ADD_WORK_ITEM_SUCCESS'
export const ADD_WORK_ITEM_FAILURE = 'app/Sprints/ADD_WORK_ITEM_FAILURE'

export const UPDATE_WORK_ITEM_REQUEST = 'app/Sprints/UPDATE_WORK_ITEM_REQUEST'
export const UPDATE_WORK_ITEM_SUCCESS = 'app/Sprints/UPDATE_WORK_ITEM_SUCCESS'
export const UPDATE_WORK_ITEM_FAILURE = 'app/Sprints/UPDATE_WORK_ITEM_FAILURE'

export const UPDATE_WORK_ITEM_STATE_REQUEST =
  'app/Sprints/UPDATE_WORK_ITEM_STATE_REQUEST'
export const UPDATE_WORK_ITEM_STATE_SUCCESS =
  'app/Sprints/UPDATE_WORK_ITEM_STATE_SUCCESS'
export const UPDATE_WORK_ITEM_STATE_FAILURE =
  'app/Sprints/UPDATE_WORK_ITEM_FAILURE'

export const DELETE_WORK_ITEM_REQUEST = 'app/Sprints/DELETE_WORK_ITEM_REQUEST'
export const DELETE_WORK_ITEM_SUCCESS = 'app/Sprints/DELETE_WORK_ITEM_SUCCESS'
export const DELETE_WORK_ITEM_FAILURE = 'app/Sprints/DELETE_WORK_ITEM_FAILURE'

export const SET_IS_ADD_WORK_ITEM_MODAL_VISIBLE_REQUEST =
  'app/Sprints/SET_IS_ADD_WORK_ITEM_MODAL_VISIBLE_REQUEST'
export const SET_IS_ADD_WORK_ITEM_MODAL_VISIBLE_SUCCESS =
  'app/Sprints/SET_IS_ADD_WORK_ITEM_MODAL_VISIBLE_SUCCESS'
export const SET_IS_ADD_WORK_ITEM_MODAL_VISIBLE_FAILURE =
  'app/Sprints/SET_IS_ADD_WORK_ITEM_MODAL_VISIBLE_FAILURE'

export const SET_IS_UPDATE_WORK_ITEM_MODAL_VISIBLE_REQUEST =
  'app/Sprints/SET_IS_UPDATE_WORK_ITEM_MODAL_VISIBLE_REQUEST'
export const SET_IS_UPDATE_WORK_ITEM_MODAL_VISIBLE_SUCCESS =
  'app/Sprints/SET_IS_UPDATE_WORK_ITEM_MODAL_VISIBLE_SUCCESS'
export const SET_IS_UPDATE_WORK_ITEM_MODAL_VISIBLE_FAILURE =
  'app/Sprints/SET_IS_UPDATE_WORK_ITEM_MODAL_VISIBLE_FAILURE'

export const SET_IS_ADD_SPRINT_MODAL_VISIBLE_REQUEST =
  'app/Sprints/SET_IS_ADD_SPRINT_MODAL_VISIBLE_REQUEST'
export const SET_IS_ADD_SPRINT_MODAL_VISIBLE_SUCCESS =
  'app/Sprints/SET_IS_ADD_SPRINT_MODAL_VISIBLE_SUCCESS'
export const SET_IS_ADD_SPRINT_MODAL_VISIBLE_FAILURE =
  'app/Sprints/SET_IS_ADD_SPRINT_MODAL_VISIBLE_FAILURE'

export const CLEAR_ERRORS = 'app/Sprints/CLEAR_ERRORS'
