/*
 *
 * Editor constants
 *
 */
export const CLEAR_STATE_SUCCESS = 'app/Editor/CLEAR_STATE_SUCCESS'

export const FETCH_SKILL_REQUEST = 'app/Editor/FETCH_SKILL_REQUEST'
export const FETCH_SKILL_SUCCESS = 'app/Editor/FETCH_SKILL_SUCCESS'
export const FETCH_SKILL_FAILURE = 'app/Editor/FETCH_SKILL_FAILURE'

export const UPDATE_SKILL_REQUEST = 'app/Editor/UPDATE_SKILL_REQUEST'
export const UPDATE_SKILL_SUCCESS = 'app/Editor/UPDATE_SKILL_SUCCESS'
export const UPDATE_SKILL_FAILURE = 'app/Editor/UPDATE_SKILL_FAILURE'

export const ADD_LEARNING_STYLE_REQUEST =
  'app/Editor/ADD_LEARNING_STYLE_REQUEST'
export const ADD_LEARNING_STYLE_SUCCESS =
  'app/Editor/ADD_LEARNING_STYLE_SUCCESS'
export const ADD_LEARNING_STYLE_FAILURE =
  'app/Editor/ADD_LEARNING_STYLE_FAILURE'

export const DELETE_LEARNING_STYLE_REQUEST =
  'app/Editor/DELETE_LEARNING_STYLE_REQUEST'
export const DELETE_LEARNING_STYLE_SUCCESS =
  'app/Editor/DELETE_LEARNING_STYLE_SUCCESS'
export const DELETE_LEARNING_STYLE_FAILURE =
  'app/Editor/DELETE_LEARNING_STYLE_FAILURE'

export const ADD_PAGE_REQUEST = 'app/Editor/ADD_PAGE_REQUEST'
export const ADD_PAGE_SUCCESS = 'app/Editor/ADD_PAGE_SUCCESS'
export const ADD_PAGE_FAILURE = 'app/Editor/ADD_PAGE_FAILURE'

export const UPDATE_PAGE_REQUEST = 'app/Editor/UPDATE_PAGE_REQUEST'
export const UPDATE_PAGE_SUCCESS = 'app/Editor/UPDATE_PAGE_SUCCESS'
export const UPDATE_PAGE_FAILURE = 'app/Editor/UPDATE_PAGE_FAILURE'

export const DELETE_PAGE_REQUEST = 'app/Editor/DELETE_PAGE_REQUEST'
export const DELETE_PAGE_SUCCESS = 'app/Editor/DELETE_PAGE_SUCCESS'
export const DELETE_PAGE_FAILURE = 'app/Editor/DELETE_PAGE_FAILURE'

export const ADD_ASSESSMENT_REQUEST = 'app/Editor/ADD_ASSESSMENT_REQUEST'
export const ADD_ASSESSMENT_SUCCESS = 'app/Editor/ADD_ASSESSMENT_SUCCESS'
export const ADD_ASSESSMENT_FAILURE = 'app/Editor/ADD_ASSESSMENT_FAILURE'

export const DELETE_ASSESSMENT_REQUEST = 'app/Editor/DELETE_ASSESSMENT_REQUEST'
export const DELETE_ASSESSMENT_SUCCESS = 'app/Editor/DELETE_ASSESSMENT_SUCCESS'
export const DELETE_ASSESSMENT_FAILURE = 'app/Editor/DELETE_ASSESSMENT_FAILURE'

export const FETCH_TEMPLATES_REQUEST = 'app/Editor/FETCH_TEMPLATES_REQUEST'
export const FETCH_TEMPLATES_SUCCESS = 'app/Editor/FETCH_TEMPLATES_SUCCESS'
export const FETCH_TEMPLATES_FAILURE = 'app/Editor/FETCH_TEMPLATES_FAILURE'

export const ADD_TEMPLATE_REQUEST = 'app/Editor/ADD_TEMPLATE_REQUEST'
export const ADD_TEMPLATE_SUCCESS = 'app/Editor/ADD_TEMPLATE_SUCCESS'
export const ADD_TEMPLATE_FAILURE = 'app/Editor/ADD_TEMPLATE_FAILURE'

export const DELETE_TEMPLATE_REQUEST = 'app/Editor/DELETE_TEMPLATE_REQUEST'
export const DELETE_TEMPLATE_SUCCESS = 'app/Editor/DELETE_TEMPLATE_SUCCESS'
export const DELETE_TEMPLATE_FAILURE = 'app/Editor/DELETE_TEMPLATE_FAILURE'

export const UPDATE_TEMPLATE_REQUEST = 'app/Editor/UPDATE_TEMPLATE_REQUEST'
export const UPDATE_TEMPLATE_SUCCESS = 'app/Editor/UPDATE_TEMPLATE_SUCCESS'
export const UPDATE_TEMPLATE_FAILURE = 'app/Editor/UPDATE_TEMPLATE_FAILURE'

export const UPDATE_SELECTED_LEARNING_STYLE_ID_REQUEST =
  'app/Editor/UPDATE_SELECTED_LEARNING_STYLE_ID_REQUEST'
export const UPDATE_SELECTED_LEARNING_STYLE_ID_SUCCESS =
  'app/Editor/UPDATE_SELECTED_LEARNING_STYLE_ID_SUCCESS'
export const UPDATE_SELECTED_LEARNING_STYLE_ID_FAILURE =
  'app/Editor/UPDATE_SELECTED_LEARNING_STYLE_ID_FAILURE'

export const UPDATE_SELECTED_ASSESSMENT_ID_REQUEST =
  'app/Editor/UPDATE_SELECTED_ASSESSMENT_ID_REQUEST'
export const UPDATE_SELECTED_ASSESSMENT_ID_SUCCESS =
  'app/Editor/UPDATE_SELECTED_ASSESSMENT_ID_SUCCESS'
export const UPDATE_SELECTED_ASSESSMENT_ID_FAILURE =
  'app/Editor/UPDATE_SELECTED_ASSESSMENT_ID_FAILURE'

export const ADD_KEYWORD_REQUEST = 'app/Editor/ADD_KEYWORD_REQUEST'
export const ADD_KEYWORD_SUCCESS = 'app/Editor/ADD_KEYWORD_SUCCESS'
export const ADD_KEYWORD_FAILURE = 'app/Editor/ADD_KEYWORD_FAILURE'

export const UPDATE_KEYWORD_REQUEST = 'app/Editor/UPDATE_KEYWORD_REQUEST'
export const UPDATE_KEYWORD_SUCCESS = 'app/Editor/UPDATE_KEYWORD_SUCCESS'
export const UPDATE_KEYWORD_FAILURE = 'app/Editor/UPDATE_KEYWORD_FAILURE'

export const DELETE_KEYWORD_REQUEST = 'app/Editor/DELETE_KEYWORD_REQUEST'
export const DELETE_KEYWORD_SUCCESS = 'app/Editor/DELETE_KEYWORD_SUCCESS'
export const DELETE_KEYWORD_FAILURE = 'app/Editor/DELETE_KEYWORD_FAILURE'

export const UPDATE_SELECTED_KEYWORD_ID_REQUEST =
  'app/Editor/UPDATE_SELECTED_KEYWORD_ID_REQUEST'
export const UPDATE_SELECTED_KEYWORD_ID_SUCCESS =
  'app/Editor/UPDATE_SELECTED_KEYWORD_ID_SUCCESS'
export const UPDATE_SELECTED_KEYWORD_ID_FAILURE =
  'app/Editor/UPDATE_SELECTED_KEYWORD_ID_FAILURE'

export const UPDATE_REORDER_CHALLENGE_QUESTION_REQUEST =
  'app/Editor/UPDATE_REORDER_CHALLENGE_QUESTION_REQUEST'
export const UPDATE_REORDER_CHALLENGE_QUESTION_SUCCESS =
  'app/Editor/UPDATE_REORDER_CHALLENGE_QUESTION_SUCCESS'
export const UPDATE_REORDER_CHALLENGE_QUESTION_FAILURE =
  'app/Editor/UPDATE_REORDER_CHALLENGE_QUESTION_FAILURE'

export const ADD_REORDER_CHALLENGE_STATEMENT_REQUEST =
  'app/Editor/ADD_REORDER_CHALLENGE_STATEMENT_REQUEST'
export const ADD_REORDER_CHALLENGE_STATEMENT_SUCCESS =
  'app/Editor/ADD_REORDER_CHALLENGE_STATEMENT_SUCCESS'
export const ADD_REORDER_CHALLENGE_STATEMENT_FAILURE =
  'app/Editor/ADD_REORDER_CHALLENGE_STATEMENT_FAILURE'

export const UPDATE_REORDER_CHALLENGE_STATEMENT_REQUEST =
  'app/Editor/UPDATE_REORDER_CHALLENGE_STATEMENT_REQUEST'
export const UPDATE_REORDER_CHALLENGE_STATEMENT_SUCCESS =
  'app/Editor/UPDATE_REORDER_CHALLENGE_STATEMENT_SUCCESS'
export const UPDATE_REORDER_CHALLENGE_STATEMENT_FAILURE =
  'app/Editor/UPDATE_REORDER_CHALLENGE_STATEMENT_FAILURE'

export const DELETE_REORDER_CHALLENGE_STATEMENT_REQUEST =
  'app/Editor/DELETE_REORDER_CHALLENGE_STATEMENT_REQUEST'
export const DELETE_REORDER_CHALLENGE_STATEMENT_SUCCESS =
  'app/Editor/DELETE_REORDER_CHALLENGE_STATEMENT_SUCCESS'
export const DELETE_REORDER_CHALLENGE_STATEMENT_FAILURE =
  'app/Editor/DELETE_REORDER_CHALLENGE_STATEMENT_FAILURE'

export const UPDATE_SELECTED_PAGE_ID_REQUEST =
  'app/Editor/UPDATE_SELECTED_PAGE_ID_REQUEST'
export const UPDATE_SELECTED_PAGE_ID_SUCCESS =
  'app/Editor/UPDATE_SELECTED_PAGE_ID_SUCCESS'
export const UPDATE_SELECTED_PAGE_ID_FAILURE =
  'app/Editor/UPDATE_SELECTED_PAGE_ID_FAILURE'
export const ADD_QUIZ_QUESTION_REQUEST = 'app/Editor/ADD_QUIZ_QUESTION_REQUEST'
export const ADD_QUIZ_QUESTION_SUCCESS = 'app/Editor/ADD_QUIZ_QUESTION_SUCCESS'
export const ADD_QUIZ_QUESTION_FAILURE = 'app/Editor/ADD_QUIZ_QUESTION_FAILURE'

export const UPDATE_QUIZ_QUESTION_REQUEST =
  'app/Editor/UPDATE_QUIZ_QUESTION_REQUEST'
export const UPDATE_QUIZ_QUESTION_SUCCESS =
  'app/Editor/UPDATE_QUIZ_QUESTION_SUCCESS'
export const UPDATE_QUIZ_QUESTION_FAILURE =
  'app/Editor/UPDATE_QUIZ_QUESTION_FAILURE'

export const DELETE_QUIZ_QUESTION_REQUEST =
  'app/Editor/DELETE_QUIZ_QUESTION_REQUEST'
export const DELETE_QUIZ_QUESTION_SUCCESS =
  'app/Editor/DELETE_QUIZ_QUESTION_SUCCESS'
export const DELETE_QUIZ_QUESTION_FAILURE =
  'app/Editor/DELETE_QUIZ_QUESTION_FAILURE'

export const UPDATE_QUIZ_LANGUAGE_REQUEST =
  'app/Editor/UPDATE_QUIZ_LANGUAGE_REQUEST'
export const UPDATE_QUIZ_LANGUAGE_SUCCESS =
  'app/Editor/UPDATE_QUIZ_LANGUAGE_SUCCESS'
export const UPDATE_QUIZ_LANGUAGE_FAILURE =
  'app/Editor/UPDATE_QUIZ_LANGUAGE_FAILURE'

export const UPDATE_QUIZ_CODE_REQUEST = 'app/Editor/UPDATE_QUIZ_CODE_REQUEST'
export const UPDATE_QUIZ_CODE_SUCCESS = 'app/Editor/UPDATE_QUIZ_CODE_SUCCESS'
export const UPDATE_QUIZ_CODE_FAILURE = 'app/Editor/UPDATE_QUIZ_CODE_FAILURE'

export const ADD_QUIZ_CHOICE_REQUEST = 'app/Editor/ADD_QUIZ_CHOICE_REQUEST'
export const ADD_QUIZ_CHOICE_SUCCESS = 'app/Editor/ADD_QUIZ_CHOICE_SUCCESS'
export const ADD_QUIZ_CHOICE_FAILURE = 'app/Editor/ADD_QUIZ_CHOICE_FAILURE'

export const UPDATE_QUIZ_CHOICE_REQUEST =
  'app/Editor/UPDATE_QUIZ_CHOICE_REQUEST'
export const UPDATE_QUIZ_CHOICE_SUCCESS =
  'app/Editor/UPDATE_QUIZ_CHOICE_SUCCESS'
export const UPDATE_QUIZ_CHOICE_FAILURE =
  'app/Editor/UPDATE_QUIZ_CHOICE_FAILURE'

export const DELETE_QUIZ_CHOICE_REQUEST =
  'app/Editor/DELETE_QUIZ_CHOICE_REQUEST'
export const DELETE_QUIZ_CHOICE_SUCCESS =
  'app/Editor/DELETE_QUIZ_CHOICE_SUCCESS'
export const DELETE_QUIZ_CHOICE_FAILURE =
  'app/Editor/DELETE_QUIZ_CHOICE_FAILURE'

export const ADD_FIB_ELEMENT_REQUEST = 'app/Editor/ADD_FIB_ELEMENT_REQUEST'
export const ADD_FIB_ELEMENT_SUCCESS = 'app/Editor/ADD_FIB_ELEMENT_SUCCESS'
export const ADD_FIB_ELEMENT_FAILURE = 'app/Editor/ADD_FIB_ELEMENT_FAILURE'

export const UPDATE_FIB_ELEMENT_REQUEST =
  'app/Editor/UPDATE_FIB_ELEMENT_REQUEST'
export const UPDATE_FIB_ELEMENT_SUCCESS =
  'app/Editor/UPDATE_FIB_ELEMENT_SUCCESS'
export const UPDATE_FIB_ELEMENT_FAILURE =
  'app/Editor/UPDATE_FIB_ELEMENT_FAILURE'

export const DELETE_FIB_ELEMENT_REQUEST =
  'app/Editor/DELETE_FIB_ELEMENT_REQUEST'
export const DELETE_FIB_ELEMENT_SUCCESS =
  'app/Editor/DELETE_FIB_ELEMENT_SUCCESS'
export const DELETE_FIB_ELEMENT_FAILURE =
  'app/Editor/DELETE_FIB_ELEMENT_FAILURE'

export const UPDATE_CODE_COMPILING_QUESTION_REQUEST =
  'app/Editor/UPDATE_CODE_COMPILING_QUESTION_REQUEST'
export const UPDATE_CODE_COMPILING_QUESTION_SUCCESS =
  'app/Editor/UPDATE_CODE_COMPILING_QUESTION_SUCCESS'
export const UPDATE_CODE_COMPILING_QUESTION_FAILURE =
  'app/Editor/UPDATE_CODE_COMPILING_QUESTION_FAILURE'

export const UPDATE_CODE_COMPILING_LANGUAGE_REQUEST =
  'app/Editor/UPDATE_CODE_COMPILING_LANGUAGE_REQUEST'
export const UPDATE_CODE_COMPILING_LANGUAGE_SUCCESS =
  'app/Editor/UPDATE_CODE_COMPILING_LANGUAGE_SUCCESS'
export const UPDATE_CODE_COMPILING_LANGUAGE_FAILURE =
  'app/Editor/UPDATE_CODE_COMPILING_LANGUAGE_FAILURE'

export const UPDATE_CODE_COMPILING_SOLUTION_REQUEST =
  'app/Editor/UPDATE_CODE_COMPILING_SOLUTION_REQUEST'
export const UPDATE_CODE_COMPILING_SOLUTION_SUCCESS =
  'app/Editor/UPDATE_CODE_COMPILING_SOLUTION_SUCCESS'
export const UPDATE_CODE_COMPILING_SOLUTION_FAILURE =
  'app/Editor/UPDATE_CODE_COMPILING_SOLUTION_FAILURE'

export const UPDATE_CODE_COMPILING_PLACEHOLDER_REQUEST =
  'app/Editor/UPDATE_CODE_COMPILING_PLACEHOLDER_REQUEST'
export const UPDATE_CODE_COMPILING_PLACEHOLDER_SUCCESS =
  'app/Editor/UPDATE_CODE_COMPILING_PLACEHOLDER_SUCCESS'
export const UPDATE_CODE_COMPILING_PLACEHOLDER_FAILURE =
  'app/Editor/UPDATE_CODE_COMPILING_PLACEHOLDER_FAILURE'

export const UPDATE_CODE_COMPILING_ADD_TEST_CASE_REQUEST =
  'app/Editor/UPDATE_CODE_COMPILING_ADD_TEST_CASE_REQUEST'
export const UPDATE_CODE_COMPILING_ADD_TEST_CASE_SUCCESS =
  'app/Editor/UPDATE_CODE_COMPILING_ADD_TEST_CASE_SUCCESS'
export const UPDATE_CODE_COMPILING_ADD_TEST_CASE_FAILURE =
  'app/Editor/UPDATE_CODE_COMPILING_ADD_TEST_CASE_FAILURE'

export const UPDATE_CODE_COMPILING_UPDATE_TEST_CASE_REQUEST =
  'app/Editor/UPDATE_CODE_COMPILING_UPDATE_TEST_CASE_REQUEST'
export const UPDATE_CODE_COMPILING_UPDATE_TEST_CASE_SUCCESS =
  'app/Editor/UPDATE_CODE_COMPILING_UPDATE_TEST_CASE_SUCCESS'
export const UPDATE_CODE_COMPILING_UPDATE_TEST_CASE_FAILURE =
  'app/Editor/UPDATE_CODE_COMPILING_UPDATE_TEST_CASE_FAILURE'

export const UPDATE_CODE_COMPILING_DELETE_TEST_CASE_REQUEST =
  'app/Editor/UPDATE_CODE_COMPILING_DELETE_TEST_CASE_REQUEST'
export const UPDATE_CODE_COMPILING_DELETE_TEST_CASE_SUCCESS =
  'app/Editor/UPDATE_CODE_COMPILING_DELETE_TEST_CASE_SUCCESS'
export const UPDATE_CODE_COMPILING_DELETE_TEST_CASE_FAILURE =
  'app/Editor/UPDATE_CODE_COMPILING_DELETE_TEST_CASE_FAILURE'

export const LOAD_SIMULATED_NODES_REQUEST =
  'app/Editor/LOAD_SIMULATED_NODES_REQUEST'
export const LOAD_SIMULATED_NODES_SUCCESS =
  'app/Editor/LOAD_SIMULATED_NODES_SUCCESS'
export const LOAD_SIMULATED_NODES_FAILURE =
  'app/Editor/LOAD_SIMULATED_NODES_FAILURE'


export const SET_DID_UPDATE_REQUEST =  'app/Editor/SET_DID_UPDATE_REQUEST'
export const SET_DID_UPDATE_SUCCESS =  'app/Editor/SET_DID_UPDATE_SUCCESS'
export const SET_DID_UPDATE_FAILURE =  'app/Editor/SET_DID_UPDATE_FAILURE'