/*
 *
 * Projects constants
 *
 */

export const FETCH_PROJECTS_REQUEST = 'app/Projects/FETCH_PROJECTS_REQUEST'
export const FETCH_PROJECTS_SUCCESS = 'app/Projects/FETCH_PROJECTS_SUCCESS'
export const FETCH_PROJECTS_FAILURE = 'app/Projects/FETCH_PROJECTS_FAILURE'

export const ADD_PROJECT_REQUEST = 'app/Projects/ADD_PROJECT_REQUEST'
export const ADD_PROJECT_SUCCESS = 'app/Projects/ADD_PROJECT_SUCCESS'
export const ADD_PROJECT_FAILURE = 'app/Projects/ADD_PROJECT_FAILURE'

export const DELETE_PROJECT_REQUEST = 'app/Projects/DELETE_PROJECT_REQUEST'
export const DELETE_PROJECT_SUCCESS = 'app/Projects/DELETE_PROJECT_SUCCESS'
export const DELETE_PROJECT_FAILURE = 'app/Projects/DELETE_PROJECT_FAILURE'

export const UPDATE_PROJECT_REQUEST = 'app/Projects/UPDATE_PROJECT_REQUEST'
export const UPDATE_PROJECT_SUCCESS = 'app/Projects/UPDATE_PROJECT_SUCCESS'
export const UPDATE_PROJECT_FAILURE = 'app/Projects/UPDATE_PROJECT_FAILURE'

export const SET_IS_UPDATE_MODAL_VISIBLE_REQUEST = 'app/Projects/SET_IS_UPDATE_MODAL_VISIBLE_REQUEST'
export const SET_IS_UPDATE_MODAL_VISIBLE_SUCCESS = 'app/Projects/SET_IS_UPDATE_MODAL_VISIBLE_SUCCESS'
export const SET_IS_UPDATE_MODAL_VISIBLE_FAILURE = 'app/Projects/SET_IS_UPDATE_MODAL_VISIBLE_FAILURE'


export const SET_IS_VISIBLE_REQUEST = 'app/Projects/SET_IS_VISIBLE_REQUEST'
export const SET_IS_VISIBLE_SUCCESS = 'app/Projects/SET_IS_VISIBLE_SUCCESS'
export const SET_IS_VISIBLE_FAILURE = 'app/Projects/SET_IS_VISIBLE_FAILURE'
