/*
 *
 * SelectedProject constants
 *
 */

export const FETCH_PROJECT_BY_ID_REQUEST =
  'app/SelectedProject/FETCH_PROJECT_BY_ID_REQUEST'
export const FETCH_PROJECT_BY_ID_SUCCESS =
  'app/SelectedProject/FETCH_PROJECT_BY_ID_SUCCESS'
export const FETCH_PROJECT_BY_ID_FAILURE =
  'app/SelectedProject/FETCH_PROJECT_BY_ID_FAILURE'

export const FETCH_PROJECT_STATS_BY_ID_REQUEST =
  'app/SelectedProject/FETCH_PROJECT_STATS_BY_ID_REQUEST'
export const FETCH_PROJECT_STATS_BY_ID_SUCCESS =
  'app/SelectedProject/FETCH_PROJECT_STATS_BY_ID_SUCCESS'
export const FETCH_PROJECT_STATS_BY_ID_FAILURE =
  'app/SelectedProject/FETCH_PROJECT_STATS_BY_ID_FAILURE'

export const FETCH_PROJECT_MEMBERS_BY_PROJECT_ID_REQUEST =
  'app/SelectedProject/FETCH_PROJECT_MEMBERS_BY_PROJECT_ID_REQUEST'
export const FETCH_PROJECT_MEMBERS_BY_PROJECT_ID_SUCCESS =
  'app/SelectedProject/FETCH_PROJECT_MEMBERS_BY_PROJECT_ID_SUCCESS'
export const FETCH_PROJECT_MEMBERS_BY_PROJECT_ID_FAILURE =
  'app/SelectedProject/FETCH_PROJECT_MEMBERS_BY_PROJECT_ID_FAILURE'

export const FETCH_PROJECT_MEMBERS_BY_FILTER_REQUEST =
  'app/SelectedProject/FETCH_PROJECT_MEMBERS_BY_FILTER_REQUEST'
export const FETCH_PROJECT_MEMBERS_BY_FILTER_SUCCESS =
  'app/SelectedProject/FETCH_PROJECT_MEMBERS_BY_FILTER_SUCCESS'
export const FETCH_PROJECT_MEMBERS_BY_FILTER_FAILURE =
  'app/SelectedProject/FETCH_PROJECT_MEMBERS_BY_FILTER_FAILURE'

export const ADD_PROJECT_MEMBER_REQUEST =
  'app/SelectedProject/ADD_PROJECT_MEMBER_REQUEST'
export const ADD_PROJECT_MEMBER_SUCCESS =
  'app/SelectedProject/ADD_PROJECT_MEMBER_SUCCESS'
export const ADD_PROJECT_MEMBER_FAILURE =
  'app/SelectedProject/ADD_PROJECT_MEMBER_FAILURE'

export const DELETE_PROJECT_MEMBER_REQUEST =
  'app/SelectedProject/DELETE_PROJECT_MEMBER_REQUEST'
export const DELETE_PROJECT_MEMBER_SUCCESS =
  'app/SelectedProject/DELETE_PROJECT_MEMBER_SUCCESS'
export const DELETE_PROJECT_MEMBER_FAILURE =
  'app/SelectedProject/DELETE_PROJECT_MEMBER_FAILURE'

export const UPDATE_PROJECT_REQUEST =
  'app/SelectedProject/UPDATE_PROJECT_REQUEST'
export const UPDATE_PROJECT_SUCCESS =
  'app/SelectedProject/UPDATE_PROJECT_SUCCESS'
export const UPDATE_PROJECT_FAILURE =
  'app/SelectedProject/UPDATE_PROJECT_FAILURE'

export const SET_IS_ADD_MEMBER_MODAL_VISIBLE_REQUEST =
  'app/SelectedProject/SET_IS_ADD_MEMBER_MODAL_VISIBLE_REQUEST'
export const SET_IS_ADD_MEMBER_MODAL_VISIBLE_SUCCESS =
  'app/SelectedProject/SET_IS_ADD_MEMBER_MODAL_VISIBLE_SUCCESS'
export const SET_IS_ADD_MEMBER_MODAL_VISIBLE_FAILURE =
  'app/SelectedProject/SET_IS_ADD_MEMBER_MODAL_VISIBLE_FAILURE'

export const SET_IS_UPDATE_MODAL_VISIBLE_REQUEST =
  'app/SelectedProject/SET_IS_UPDATE_MODAL_VISIBLE_REQUEST'
export const SET_IS_UPDATE_MODAL_VISIBLE_SUCCESS =
  'app/SelectedProject/SET_IS_UPDATE_MODAL_VISIBLE_SUCCESS'
export const SET_IS_UPDATE_MODAL_VISIBLE_FAILURE =
  'app/SelectedProject/SET_IS_UPDATE_MODAL_VISIBLE_FAILURE'
